In [4]:
#import library
import pandas as pd
import numpy as np


In [5]:
#load data
data = pd.read_csv("./train.csv")

In [6]:
data.head()

Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0            1  22.0   7.2500    0      1     0       0       0       0   
1            2  38.0  71.2833    1      1     0       0       0       0   
2            3  26.0   7.9250    1      0     0       0       0       0   
3            4  35.0  53.1000    1      1     0       0       0       0   
4            5  35.0   8.0500    0      0     0       0       0       0   

   zero.4    ...     zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0       0    ...           0        0        0       3        0        0   
1       0    ...           0        0        0       1        0        0   
2       0    ...           0        0        0       3        0        0   
3       0    ...           0        0        0       1        0        0   
4       0    ...           0        0        0       3        0        0   

   Embarked  zero.17  zero.18  2urvived  
0       2.0        0        0         0  
1       0.0        0        0         1  
2       2.0        0        0         1  
3       2.0        0        0         1  
4       2.0        0        0         0  

[5 rows x 28 columns]

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
Passengerid    1309 non-null int64
Age            1309 non-null float64
Fare           1309 non-null float64
Sex            1309 non-null int64
sibsp          1309 non-null int64
zero           1309 non-null int64
zero.1         1309 non-null int64
zero.2         1309 non-null int64
zero.3         1309 non-null int64
zero.4         1309 non-null int64
zero.5         1309 non-null int64
zero.6         1309 non-null int64
Parch          1309 non-null int64
zero.7         1309 non-null int64
zero.8         1309 non-null int64
zero.9         1309 non-null int64
zero.10        1309 non-null int64
zero.11        1309 non-null int64
zero.12        1309 non-null int64
zero.13        1309 non-null int64
zero.14        1309 non-null int64
Pclass         1309 non-null int64
zero.15        1309 non-null int64
zero.16        1309 non-null int64
Embarked       1307 non-null float64
zero.17     

In [8]:
#determining the target column
columns_target = ['2urvived']

#column used for predicting :age,sex,Pclass,Fare

columns_train = ['Age','Fare','Sex','Pclass']

In [9]:
#separate the data
X = data[columns_train]
Y = data[columns_target]

In [10]:
#check for NaN values in columns used for prediction
X['Sex'].isnull().sum()
X['Pclass'].isnull().sum()
X['Fare'].isnull().sum()
X['Age'].isnull().sum()

0

In [11]:
#split data to training and testing
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.33,random_state=42)

In [12]:
#training the model
from sklearn.linear_model import LogisticRegression

In [13]:
lrm = LogisticRegression()
lrm.fit(X_train, Y_train)
print(lrm)

C:\Users\Lenovo-User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)


In [14]:
print(lrm.predict(X_test[0:1]))
print(lrm.predict(X_test[0:10]))
print(lrm.score(X_test,Y_test))

[0]
[0 0 0 0 0 0 0 1 0 0]
0.7800925925925926


In [15]:
#training the model
from sklearn import svm
svlm = svm.LinearSVC()
svlm.fit(X_train, Y_train)
print(svlm)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)


C:\Users\Lenovo-User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [16]:
print(svlm.predict(X_test[0:1]))
print(svlm.predict(X_test[0:10]))
print(svlm.score(X_test,Y_test))

[0]
[0 0 0 0 0 0 0 0 0 0]
0.7361111111111112


In [17]:
from sklearn.neighbors import KNeighborsRegressor

In [18]:
knn = KNeighborsRegressor(n_neighbors=1)

In [19]:
knn.fit(X_train, Y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=1, p=2,
          weights='uniform')

In [24]:
print(knn.predict(X_test[0:10]))
print(knn.score(X_test,Y_test))

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]]
-0.7040714995034758


In [28]:
#finding error percetage for logistic resgression

from sklearn import metrics
predictions = lrm.predict(X_test) 
print('Mean Absolute Error:', metrics.mean_absolute_error(Y_test, predictions))
print('Mean Squared Error:', metrics.mean_squared_error(Y_test, predictions))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test,predictions)))

Mean Absolute Error: 0.2199074074074074
Mean Squared Error: 0.2199074074074074
Root Mean Squared Error: 0.46894286155928144


In [31]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
y_pred = np.array(lrm.predict(X_train))
y_actual = np.array(Y_train)
print(confusion_matrix(y_pred,y_actual))

[[594 135]
 [ 55  93]]


In [32]:
print(accuracy_score(y_pred,y_actual)*100)

78.33523375142532
